services:
  database:
    container_name: BowlingTrackerSupreme.Database
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Netcompany-123
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - bowlingtrackersupreme_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080/tcp
    volumes:
      - bowlingtrackersupreme_data:/var/lib/postgresql/data

volumes:
  bowlingtrackersupreme_data:

