// <auto-generated />
using System;
using BowlingTrackerSupreme.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BowlingTrackerSupreme.Infrastructure.Migrations
{
    [DbContext(typeof(BowlingTrackerSupremeDbContext))]
    [Migration("20250120182639_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Frame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FirstRollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FrameNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlayerGameGameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlayerGamePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SecondRollId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FirstRollId");

                    b.HasIndex("SecondRollId");

                    b.HasIndex("PlayerGamePlayerId", "PlayerGameGameId");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WinningPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WinningPlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.PlayerGame", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EightFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FifthFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FirstFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FourthFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NinthFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SecondFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SeventhFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SixthFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenthFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ThirdFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("EightFrameId");

                    b.HasIndex("FifthFrameId");

                    b.HasIndex("FirstFrameId");

                    b.HasIndex("FourthFrameId");

                    b.HasIndex("GameId");

                    b.HasIndex("NinthFrameId");

                    b.HasIndex("SecondFrameId");

                    b.HasIndex("SeventhFrameId");

                    b.HasIndex("SixthFrameId");

                    b.HasIndex("TenthFrameId");

                    b.HasIndex("ThirdFrameId");

                    b.ToTable("PlayerGames");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Roll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PinsHit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.ToTable("Rolls");
                });

            modelBuilder.Entity("GamePlayer", b =>
                {
                    b.Property<Guid>("GameParticipationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameParticipationId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("GamePlayer");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Frame", b =>
                {
                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Roll", "FirstRoll")
                        .WithMany()
                        .HasForeignKey("FirstRollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Roll", "SecondRoll")
                        .WithMany()
                        .HasForeignKey("SecondRollId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.PlayerGame", null)
                        .WithMany("AllFrames")
                        .HasForeignKey("PlayerGamePlayerId", "PlayerGameGameId");

                    b.Navigation("FirstRoll");

                    b.Navigation("SecondRoll");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Game", b =>
                {
                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Player", "WinningPlayer")
                        .WithMany()
                        .HasForeignKey("WinningPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WinningPlayer");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.PlayerGame", b =>
                {
                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "EightFrame")
                        .WithMany()
                        .HasForeignKey("EightFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "FifthFrame")
                        .WithMany()
                        .HasForeignKey("FifthFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "FirstFrame")
                        .WithMany()
                        .HasForeignKey("FirstFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "FourthFrame")
                        .WithMany()
                        .HasForeignKey("FourthFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Game", "Game")
                        .WithMany("PlayerGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "NinthFrame")
                        .WithMany()
                        .HasForeignKey("NinthFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "SecondFrame")
                        .WithMany()
                        .HasForeignKey("SecondFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "SeventhFrame")
                        .WithMany()
                        .HasForeignKey("SeventhFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "SixthFrame")
                        .WithMany()
                        .HasForeignKey("SixthFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "TenthFrame")
                        .WithMany()
                        .HasForeignKey("TenthFrameId");

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", "ThirdFrame")
                        .WithMany()
                        .HasForeignKey("ThirdFrameId");

                    b.Navigation("EightFrame");

                    b.Navigation("FifthFrame");

                    b.Navigation("FirstFrame");

                    b.Navigation("FourthFrame");

                    b.Navigation("Game");

                    b.Navigation("NinthFrame");

                    b.Navigation("Player");

                    b.Navigation("SecondFrame");

                    b.Navigation("SeventhFrame");

                    b.Navigation("SixthFrame");

                    b.Navigation("TenthFrame");

                    b.Navigation("ThirdFrame");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Roll", b =>
                {
                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Frame", null)
                        .WithMany("AllRolls")
                        .HasForeignKey("FrameId");
                });

            modelBuilder.Entity("GamePlayer", b =>
                {
                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GameParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BowlingTrackerSupreme.Domain.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Frame", b =>
                {
                    b.Navigation("AllRolls");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.Game", b =>
                {
                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("BowlingTrackerSupreme.Domain.Models.PlayerGame", b =>
                {
                    b.Navigation("AllFrames");
                });
#pragma warning restore 612, 618
        }
    }
}
